- docs/adr/0004-wdqs-tarball-content.md
- docs/adr/index.md
https://phabricator.wikimedia.org/T267749
> Add WDQS tarball contents/packaging ADR

- docs/adr/0003-tarball-contents.md
- docs/adr/index.md
https://phabricator.wikimedia.org/T267754
> Add Wikibase tarball contents ADR

- README.md
- test_scripts/selenium/README.md
- test_scripts/selenium/queryservice-ui/queryservice-ui.page.js
- test_scripts/selenium/specs/item.js
- test_scripts/test_docker.sh
Extending the current test-case to adding a property and verifying the results a bit more in detail
> add property to item for testing

- docs/adr/0002-tarball-hosting.md
- docs/adr/index.md
https://phabricator.wikimedia.org/T268024
decision is -> use releases.wikimedia.org
> Add Wikibase Tarball Hosting ADR

- .github/workflows/built_and_test.yml
- Docker/DockerWikibase/Dockerfile
- Dockerfile
- build_github.sh
- build_scripts/build_wikibase.sh
Adds the vendor folder to the tarball but then removes it again when creating the docker image.
> add vendor folder to tarball

- docs/adr/0006-pipline-runner.md
please fill out any missing information
> ADR_006 - pipeline runner

- .github/workflows/built_and_test.yml
- Docker/build/Wikibase/Dockerfile
- Docker/build/Wikibase/LocalSettings.php.template
- Makefile
- build/build_wikibase_docker.sh
- test/docker-compose.yml
- test/test_suite.sh
- update_cache.sh
Bug: [T272599](https://phabricator.wikimedia.org/T272599)
> Add ElasticSearch related extensions

- Docker/test/selenium/Dockerfile
- Docker/test/selenium/README.md
- Docker/test/selenium/helpers/default-functions.js
- Docker/test/selenium/specs/repo/elasticsearch.js
- Docker/test/selenium/specs/repo/special-version.js
- Docker/test/selenium/wdio.conf.js
- test/config/repo/wikibase/run-jobs.sh
- test/docker-compose-selenium-test.yml
- test/docker-compose.yml
https://phabricator.wikimedia.org/T272600
> Add ElasticSearch tests

- Docker/publish/tag_git/tag_git.sh
- build/build_queryservice_ui.sh
- build/clean_repo.sh
- build/clone_repo.sh
- build/write_git_metadata.sh
> [1.T272577] add helper bash scripts for cloning and cleaning

- Docker/test/selenium/Dockerfile
- Docker/test/selenium/README.md
- Docker/test/selenium/helpers/default-functions.js
- Docker/test/selenium/specs/repo/elasticsearch.js
- Docker/test/selenium/specs/repo/special-version.js
- test/config/repo/wikibase/run-jobs.sh
- test/docker-compose-selenium-test.yml
- test/docker-compose.yml
- test/run_selenium.sh
- test/test_suite.sh
- dont install node_modules if it was copied on test
- shutdown all suites
> test improvements

- Dockerfile
- build.sh
- build/build_elasticsearch_docker.sh
- build/build_mediawiki_docker.sh
- build/build_queryservice_docker.sh
- build/build_queryservice_ui_docker.sh
- build/build_quickstatements_docker.sh
- build/build_wikibase_bundle_docker.sh
- build/build_wikibase_docker.sh
- variables.env
- gzip compression to wait less
- extension branch name
> add some local.env overrides

- Docker/build/QuickStatements/Dockerfile
- Docker/build/Wikibase/Dockerfile
- Docker/build/WikibaseBundle/Dockerfile
- Dockerfile
- build.sh
- build/build_composer_docker.sh
- build/build_quickstatements_docker.sh
- build/build_wikibase.sh
- build/build_wikibase_bundle_docker.sh
- build/build_wikibase_docker.sh
- variables.env
Adds these two variables and uses them when in need of composer
COMPOSER_IMAGE_NAME=docker-registry.wikimedia.org/releng/composer-package-php72
COMPOSER_IMAGE_VERSION=latest
> Use wikimedia composer image

- Docker/build/QueryServiceUI/Dockerfile
- build/build_queryservice_ui.sh
> the wdqs-frontend.tar.gz contains a leading folder

- Docker/test/selenium/specs/federated-properties/item.js
- Docker/test/selenium/specs/repo/queryservice.js
- test/reporter/report.js
> re-order some test files

- variables.env
docker-registry.wikimedia.org/releng/composer-php72
> change composer image

- Docker/test/selenium/helpers/default-functions.js
- Docker/test/selenium/specs/federated-properties/item.js
- Docker/test/selenium/specs/federated-properties/prefetching.js
- test/suite-config/fedprops/LocalSettings.php
-  [x]  Should test if prefetching works as intended
-  [x]  Manual setup of entity sources should no longer be necessary
> [T276074] Add some federated-properties tests for prefetching 

- .github/workflows/built_and_test.yml
- .github/workflows/test.yml
- Docker/build/Wikibase/Dockerfile
- Docker/build/Wikibase/LocalSettings.php.template
- Docker/test/selenium/helpers/default-functions.js
- Docker/test/selenium/package.json
- Docker/test/selenium/specs/pingback/pingback.js
- test/docker-compose-selenium-test.yml
- test/suite-config/pingback/LocalSettings.php
- test/suite-config/pingback/beacon/beacon.js
- test/suite-config/pingback/docker-compose.override.yml
Tests the pingback by intercepting the message and checking the database that it was marked as sent
> [T276075] Test pingback

- Docker/test/selenium/specs/repo/elasticsearch.js
- UpdateSearchIndexConfig does not require the job queue
- Wait 10 seconds after indexing
> Some changes to elasticsearch.js

- Docker/test/selenium/wdio.conf.js
- docs/topics/pipeline.md
- test/docker-compose-selenium-test.yml
Makes it easier to have this locally set to something higher when debugging
> [T276939.1] Add SELENIUM_LOG_LEVEL variable

- Docker/build/WikibaseBundle/Dockerfile
- Docker/build/WikibaseBundle/LocalSettings.cldr.php
- build/build_wikibase_bundle_docker.sh
- update_cache.sh
Could not come to think of any way to test this!
> [T276929] Add cldr to bundle

- Docker/build/WikibaseBundle/Dockerfile
- Docker/build/WikibaseBundle/LocalSettings.UniversalLanguageSelector.php
- Docker/test/selenium/helpers/default-functions.js
- Docker/test/selenium/specs/repo/special-version.js
- Docker/test/selenium/specs/repo/universal-language-selector.js
- build/build_wikibase_bundle_docker.sh
- update_cache.sh
> [T276920] Add UniversalLanguageSelector to bundle

- Docker/test/selenium/wdio.conf.js
> Raise selenium tests timeouts by 50%

- Docker/publish/upload_tar/publish.sh
- docs/topics/publishing.md
- publish/docker-compose.yml
adds the option to tarball uploading + some docs on how to use it
> [T272826] Add tarball dry run

- .github/workflows/built_and_test.yml
seems this wasn't added to the default test run
> Re-enable elasticsearch

- docs/topics/pipeline.md
- docs/topics/publishing.md
- publish/docker-compose.yml
`RELEASE_USER` should be set via `local.env`.
> Don't set RELEASE_USER to $USER

- Docker/test/selenium/pages/entity/property.page.js
- Docker/test/selenium/specs/repo/property.js
Adds the last browser tests to https://phabricator.wikimedia.org/T268716
> [T268716] Add property reference + statement test

- Docker/test/selenium/specs/repo-client/item.js
Should make it more obvious that this worked correctly.
> Add assertions to "Should be able to insert interwiki links"

- Docker/test/selenium/specs/elasticsearch/elasticsearch.js
> [T279538.4] Remove unused elasticsearch tests

- Docker/test/selenium/specs/repo/property.js
oopsie, fixes hardcoded property id
> Remove hardcoded property ids from repo/property.js

- .github/workflows/built_and_test.yml
latest isn't really as useful as specifying what wmde.N number was used
> Use the WMDE_RELEASE_VERSION instead of latest

- Docker/build/WDQS/README.md
https://phabricator.wikimedia.org/T280772
> Add some notes on security for WDQS

- example/docker-compose.yml
- example/template.env
drops the mysql part in the example
> example docker: use the same names as in the image

- Docker/build/WDQS-frontend/Dockerfile
- removed seemingly unused python
> Install dependencies no longer compatible.

- Docker/build/QuickStatements/Dockerfile
> Add intl php extension to QuickStatements Image

- docs/topics/publishing.md
https://phabricator.wikimedia.org/T281098
> Add some docs on how to manually verify a build

- Makefile
- remove log on clean
- output what versions are used in the logs
> some version fixes

- Docker/test/selenium/helpers/default-functions.js
- Docker/test/selenium/specs/quickstatements/quickstatements.js
- Docker/test/selenium/wdio.conf.js
- test/suite-config/quickstatements/LocalSettings.php
- test/suite-config/quickstatements/curl-test/entrypoint.sh
- test/suite-config/quickstatements/docker-compose.override.yml
- test/suite-config/quickstatements/wikibase/extra-install.sh
- test/suite-config/repo_client/curl-test/entrypoint.sh
things that doesn't work.
- Add qualifier with datatype string maybe other datatypes do not work either.
- sitelink creation doesn't seem to work for some reason.
> Add some more qs tests

- docs/adr/0013-docker-latest-tag.md
One part of https://phabricator.wikimedia.org/T275217
> Add ADR-13 on latest tag

- docs/adr/0016-updating-non-wmde-software.md
Related to https://phabricator.wikimedia.org/T272538
> Added "ADR" on releasing and maintaining non WMDE software

- .github/workflows/built_and_test.yml
- example/docker-compose.yml
- test/test_example.sh
follows example then 
- waits for wdqs to start polling
- checks mw for main page
- checks queryservice ui
> Add test for docker-example

- .github/workflows/built_and_test.yml
This potentially would have caught https://phabricator.wikimedia.org/T286334
If this ends up being red then that's true, and https://github.com/wmde/wikibase-release-pipeline/pull/196 will need merging first
> example test: ensure all expected services are up

- Docker/build/WikibaseBundle/LocalSettings.d.template/SyntaxHighlight_GeSHi.php
- Docker/test/selenium/specs/repo/extensions/syntax-highlight.js
- update_cache.sh
- versions/wmde3-alpha.env
on wmde.3 https://github.com/wmde/wikibase-release-pipeline/actions/runs/1174290313
> Add SyntaxHighlight to wmde3-alpha.env

- Docker/test/selenium/package-lock.json
- Docker/test/selenium/package.json
Bug: T288443
https://phabricator.wikimedia.org/T288443
> Update wdio-wikibase in Docker/test/selenium to 5.1.0

- docs/index.md
- docs/topics/test-system.md
Adds some notes on the undocumented test-system.
> Add some notes on test-system

- example/template.env
update template env with password requirements
> Update template env to mention password requirements

- .github/workflows/built_and_test.yml
- .github/workflows/test.yml
We could even have something like 15 minutes but lets give it some headroom well under 6 hours.
> [T296066.1] Add 30 min timeout for tests

- example/docker-compose.extra.yml
- MW_ELASTIC_HOST
- MW_ELASTIC_PORT
> Add missing ENV vars to example jobrunner

- example/docker-compose.yml
fix typo and start passing it down
> use WIKIBASE_HOST in example env

- test/suite-config/repo_client/client/LocalSettings.php.template
- test/suite-config/repo_client/docker-compose.override.yml
- use port 80 for client
- don't load repo only extensions
> make client work on host

- docs/topics/upgrading.md
- example/README.md
- example/docker-compose.extra.yml
- example/docker-compose.yml
Move the unused QS mount to extra file
Update upgrading instructions to work with reality
> Quickstatements mount only used by extra + update upgrading instructions

- Docker/test/selenium/specs/repo/extensions/syntax-highlight.js
- Docker/test/selenium/specs/repo/extensions/wikibase-edtf.js
> Fix the extension name for WikibaseEdtf and SyntaxHighlight in tests

- docs/topics/publishing.md
Announcement actually go to three channels
> Updated mailing list URL, added more channels

- docs/topics/publishing.md
Per data in https://wikitech.wikimedia.org/wiki/SRE/Production_access#SSH_configuration
> Updated bastion host name in publishing instructions

- build/build_extension.sh
- build/build_wikibase.sh
> Stop using custom cloning / cleaning for

- docs/topics/testing.md
- upgrade bundle
- example
- how to stop containers
> Add some missing documentation for the testing scripts

- Docker/test/selenium/specs/elasticsearch/elasticsearch.js
- Docker/test/selenium/specs/repo/extensions/nuke.js
Rewrites the waitUntil usage that was broken.
> Fix broken waitUntil usage

- example/template.env
previous description was phrased as an error message that would be shown to the user after they entered a weak password
> adjusted description of password requirements

- .github/workflows/built_and_test.yml
- test/upgrade/old-versions/latest-base.env
- test/upgrade/old-versions/lts-base.env
- test/upgrade/old-versions/wmde.2-bundle.env
- test/upgrade/old-versions/wmde.2.env
- test/upgrade/old-versions/wmde.3-bundle.env
- test/upgrade/old-versions/wmde.3.env
Adds the missing ones and removes some that probably doesn't mean anything to anyone.
> Add missing upgrade tests

- docs/topics/upgrading.md
> Fix typo in upgrading.md

- test/test_example.sh
> Default test-example to example suite

- build/build_wikibase_bundle_docker.sh
- build/clean_repo.sh
- build/clone_repo.sh
- update_cache.sh
This removes some excessive logging that has been going on
> Reduce verbosity

- Docker/test/selenium/wdio.conf.js
- example/docker-compose.extra.yml
- example/docker-compose.yml
- example/template.env
- test/docker-compose.example.yml
- test/test_example.sh
- Move public env var to .env
- Add testing
> Fix QuickStatements example

- Docker/test/selenium/package-lock.json
- Docker/test/selenium/package.json
- Docker/test/selenium/wdio.conf.js
- docs/topics/pipeline.md
- docs/topics/testing.md
During some work on wikbase.cloud there was a requirement to populate the wikibase instance with some stuff to try out migrations.
Some work was put in here to make it possible to run specific tests against a minikube instance.
https://github.com/wbstack/api/pull/331
> Wbaas test changes

- Docker/build/WikibaseBundle/LocalSettings.d.template/CirrusSearch.php
- Docker/build/WikibaseBundle/LocalSettings.d.template/WikibaseCirrusSearch.php
> Only load CirrusSearch extensions if MW_ELASTIC_HOST is set

- Docker/build/WDQS/README.md
Fixes a broken link in WDQS README to the dumpRdf.php documentation.
> Fix link to dumpRdf.php documentation

- example/docker-compose.yml
Having the jobs run with the same settings as wikibase is probably what wou want.
> Add localsettings comment to wikibase_jobrunner

- CHANGES.md
- Docker/build/Wikibase/Dockerfile
- test/suite-config/confirm_edit/LocalSettings.php
- test/suite-config/elasticsearch/LocalSettings.php
- test/suite-config/example/LocalSettings.php
- test/suite-config/fedprops/LocalSettings.php
- test/suite-config/pingback/LocalSettings.php
- test/suite-config/quickstatements/LocalSettings.php
- test/suite-config/repo/LocalSettings.php
- test/suite-config/repo_client/LocalSettings.php
- test/suite-config/repo_client/client/LocalSettings.php.template
- test/suite-config/repo_client/repo/LocalSettings.php.template
- test/test_upgrade.sh
- Ignore deprecation warnings in wikibase php.ini
- Remove error_reporting setting from localsettings files
- Note in changes.md
> wmde11: Set error_reporting in wikibase php.ini file

- docs/topics/publishing.md
bast3005 has been decomissioned
> Updated WMF bastion host name

- Docker/test/selenium/Dockerfile
- docs/topics/pipeline.md
- test/run_selenium.sh
- test/test_upgrade.sh
https://phabricator.wikimedia.org/T341469
> T341469: use docker layer cache for selenium container build

- .github/workflows/test_example.yml
https://phabricator.wikimedia.org/T346210
> T346210 test_example action is wasteful

- test/specs/repo/extensions/nuke.js
https://phabricator.wikimedia.org/T347117
> T347117 Repo Nuke Test flaky

- test/scripts/test_suite.sh
Checks if an image is already loaded before loading it.
> T346740 Avoid reloading images

- test/scripts/test_suite.sh
https://phabricator.wikimedia.org/T348113
> T348113 Supress image loading logging

- test/helpers/WDIOMediawikiScreenshotPatch.js
- test/helpers/blazegraph.js
- test/helpers/default-functions.js
- test/helpers/json-reporter.js
- test/helpers/pages/WDIOMediawikiPagePatch.js
- test/specs/elasticsearch/elasticsearch.js
- test/specs/fedprops/item.js
- test/specs/fedprops/prefetching.js
- test/specs/quickstatements/quickstatements.js
- test/specs/repo/api.js
- test/specs/repo/extensions/entityschema.js
- test/specs/repo/extensions/scribunto.js
- test/specs/repo/extensions/syntax-highlight.js
- test/specs/repo/queryservice.js
- test/specs/repo_client/extensions/scribunto-item.js
- test/specs/repo_client/interwiki-links.js
- test/specs/repo_client/item.js
- test/wdio.conf.js
Specify imports rather than importing the entire module where possible. Refactoring and reformatting of `defaultFunctions`.
> Specify Imports

- .github/workflows/build_and_test.yml
Automatically run CI on all `mw-*` branches
> Test mw-* branches

- .github/workflows/build_and_test.yml
see https://github.com/wmde/wikibase-release-pipeline/pull/505 for details
> Backport #505 to 1.40

- test/.eslintrc.json
- test/helpers/pages/special/list-properties.page.ts
- test/helpers/pages/special/new-property.page.ts
- test/specs/repo/special-property.ts
- test/suites/repo/LocalSettings.php
> Backport #493 to 1.39

- .github/workflows/build_and_test.yml
> Backport #505 to 1.39

- .github/workflows/build_and_test.yml
https://phabricator.wikimedia.org/T351290
❗ **cherry pick to `mw-` branches**
> feat: trigger upload ghcr github action workflow on prep-mw- branches as well

- .github/workflows/build_and_test.yml
> Backport #514 to 1.40

- .github/workflows/build_and_test.yml
See https://github.com/wmde/wikibase-release-pipeline/pull/514 for details
> Backport #514 to 1.39

- .github/workflows/build_and_test.yml
> fix(github-actions-workflow): ghcr upload base_ref check (#518)

- Docker/publish/upload_tar/publish.sh
- docs/topics/publishing.md
- docs/topics/test-system.md
- publish/docker-compose.yml
- publish/tar-nodocker.sh
https://github.com/wmde/wikibase-release-pipeline/pull/512
> fix: gh built artifact names (#512)

- .github/workflows/build_and_test.yml
https://phabricator.wikimedia.org/T352962
> T352962 fix: ghcr docker image upload

- test/helpers/pages/entity/property.page.ts
- test/specs/repo/property.ts
https://phabricator.wikimedia.org/T350878
> T350878 (1): Covers lines 18 and 21 of Product Verification sheet (Property history)

- build/QuickStatements/README.md
- build/QuickStatements/config.json
- build/QuickStatements/entrypoint.sh
- example/docker-compose.extra.yml
- test/suites/quickstatements/docker-compose.override.yml
https://phabricator.wikimedia.org/T349806 and https://phabricator.wikimedia.org/T354260
> T349806 - Fix Quickstatements image

- .github/dependabot.yml
- .github/workflows/_build_test.yml
Keep lint dependencies up to date
> Check Lint Dependencies

- CHANGES.md
- build.sh
Reverts wmde/wikibase-release-pipeline#616
> Revert "test: release automation trigger"

- variables.env
https://phabricator.wikimedia.org/T354644
> Release WMDE.17

- CHANGES.md
- example/template.env
Update Example (and correct date)
> Post-Release WMDE.20 Example

- build.sh
```
❱ ./build.sh --no-cache
sha256:755a6022735c5af240075c1c2fa984271845b5c22b914ab59411c8e97a38e7e9
sha256:7f3251ebfddbd98293bd3f8922cd8a35d750f6e1f885a004ca94d3cdfe58aed2
sha256:800f3139f6bd182cb6e9e533f26ec19c78d25e17040fa0282d7cd030537e73be
sha256:e11e079004d341e07a4a73b5c35f8a5a7b834f22235ce31d4a3320e89c1f5f03
sha256:190f0a3fcc9d796dab1067bfc58e9ec0632acf2c004e5bc11cfb159bb5d97cad
sha256:ba5d1673e3a187d92de3c532ce7447d145be1b1061931a95e5896dc77f597670
sha256:4cc739aebceccb9b8b98baf88e337a6776b71b97dea1ffbc6b5e0e6410016fa8
Succeeded after 01:44  
```
> feat(build): make ./build.sh (all) run builds in parallel 😈 #backport

- README.md
- deploy/README.md
- deploy/docker-compose.yml
https://phabricator.wikimedia.org/T367745
> T367745: update product names in docs

- build.sh
- build/QuickStatements/Dockerfile
- build/Wikibase/Dockerfile
https://phabricator.wikimedia.org/T368145
> T368145: remove build args

- .github/workflows/build_test_publish_release.yml
- variables.env
https://phabricator.wikimedia.org/T367043
> T367043: adjust git tagging

- build/QuickStatements/README.md
- build/WDQS-frontend/README.md
- deploy/docker-compose.yml
https://phabricator.wikimedia.org/T368886
> T368886: bump traefik to 3.1

- deploy/docker-compose.yml
https://phabricator.wikimedia.org/T369133
> T369133: job runner auto restart

- test/package-lock.json
- test/package.json
- test/specs/repo/extensions/universal-language-selector.ts
- test/specs/repo/property.ts
This needs to also be merged down to the 1.0.0 branch to prove that it works.
> Make tests work across all releases

- README.md
https://phabricator.wikimedia.org/T367024
> T367024: release checklist

- deploy/config/README.md
- deploy/template.env
- test/suites/deploy/deploy.conf.ts
https://phabricator.wikimedia.org/T369358
> T369358: product name in template.env

- README.md
https://phabricator.wikimedia.org/T370035
> T370035 docs: add release checklist item: update dockerhub

- variables.env
> T365569: release 3.0.0 (WBS Deploy 3.0.0) - merging release branch back to main

- CHANGES.md
> T368255: release 1.0.0 (WBS Deploy 1.0.0) - merging release branch back to main

- build/Wikibase/README.md
> docs: mention and link mediawiki shipped extensions

- deploy/README.md
> docs: fix backup script volume names

- deploy/docker-compose.yml
> chore: bump deploy to version 2

- test/helpers/default-functions.ts
- test/setup/make-test-settings.ts
- test/specs/repo/extensions/universal-language-selector.ts
- test/specs/repo/property.ts
- test/specs/repo/special-version.ts
- test/types/wdio.d.ts
Get MediaWiki version from API in order to branch in tests.
> test: get current mediawiki version from api

- .github/workflows/_build_test.yml
- .github/workflows/build_publish_image_release.yml
- .github/workflows/create_release.yml
More info: https://github.com/actions/runner-images/issues/10636
> ci: switch pipeline runner to ubuntu-24.04 (T383540)

- .github/actions/setup-environment/action.yml
- .github/workflows/_build_test.yml
- .github/workflows/build_publish_image_release.yml
- .github/workflows/build_test_main.yml
- .github/workflows/build_test_pr.yml
- .github/workflows/create_release.yml
Increases ratelimit at dockerhub by logging in also for just pulling. Tries to work around issues like https://github.com/wmde/wikibase-release-pipeline/actions/runs/13669341458/job/38216571627#step:5:82
ready
n/a
> feat: login to dockerhub registry to extend rate limit

- .gitignore
- deploy/README.md
- deploy/config/Extensions.php
- deploy/config/extensions/README.md
- deploy/docker-compose.yml
- test/specs/repo/extensions/user-defined-extensions.ts
- test/suites/docker-compose.override.yml
- test/suites/repo/LocalSettings.php
- test/suites/repo/docker-compose.override.yml
- test/suites/repo/extensions/WikibaseSuiteTestExtension/extension.json
Implements and documents a way to add user defined extensions via deploy.
ready to be reviewed, should be merged after #834 
#834
> feat: user defined extensions

- deploy/docker-compose.yml
https://phabricator.wikimedia.org/T389595
> chore: allow traefik updates within 3.x.x

- build/wikibase/jobrunner-entrypoint.sh
Continuation of: https://github.com/wmde/wikibase-release-pipeline/pull/801
> T378941 - Confirm CI passed on PR pushes and merge to main (de-duped)

- .eslintrc-whitespace.json
- .eslintrc.json
- lint.sh
- pnpm-workspace.yaml
- test/cli.ts
- No longer does our linting lint within deploy/config/extensions. As it was if you had any locally installed extensions their entire directories would be listed.
- Fixes some outstanding linting issues / warnings
> chore: fix linting issues and update config
