- diagrams/Dockerfile
- diagrams/README.md
I looked at (and copied) these files for use making some other diagrams.
I saw this as one small improvement to make the README slightly easier to follow (purley as it will have less words)
> Add workdir for diagrams to Dockerfile

- docs/adr/0011-wikibase-bundle.md
- docs/adr/index.md
- Add ADR on decision not to publish/create a wikibase bundle tarball, but create a bundle and base docker image.
- Add index
> ADR0011 - Wikibase bundle tarball/docker image

- docs/adr/0009-non-WMDE-release-notes.md
WMDE will not have a "release notes" document for the other party's software which does not provide such a document, but it is not impossible to imagine that we'll know there is a huge changes in, say, Quick Statements, we still might inform users about it - just in a different form than release notes document.
> Made a point on not communicated changes in non-WMDE software less dramatic

- build/build_mediawiki.sh
- test/suite-config/fedprops/LocalSettings.php
- mw REL1_35 for some reasons contain the Vector folder so this is now
removed always and cloned.
- Fedprops auto-setup is not in REL1_35 so we can use the manual setup
to skip relying on it.
> some fixes for building REL1_35 branch

- variables.env
Seems we need 7.3 to build REL1_35
https://github.com/wmde/wikibase-release-pipeline/actions/runs/580831354
> bump composer php version

- docs/adr/0012-versioning.md
https://phabricator.wikimedia.org/T273889
> ADR0012 - versioning scheme & branching

- Docker/publish/download_artifacts/download_artifacts.py
This helped me figuring out that my access token didn't have enough rights when testing.
> download_artifacts: Nicely show github API errors

- test/reporter/report.js
Sometimes there is no file on these errors and then the reporter crashes
instead, which is less than ideal.
> Fix error on reporter

- .github/workflows/test.yml
- Docker/test/selenium/package.json
- Docker/test/selenium/specs/elasticsearch/elasticsearch.js
- Makefile
- test/suite-config/elasticsearch/LocalSettings.php
Seems running this test with the repo suite is not ideal as there is an
uncertainty of when this test will get executed and how many jobs will
be required etc.
This change moves elasticsearch testing to it's own suite. Some additional assertions now that we know the exact number of jobs required.
> Isolate elasticsearch

- Docker/test/selenium/data/interwiki-link.sql
- Docker/test/selenium/specs/repo-client/item.js
- test/config/client/wikibase/extra-install-client.sh
- test/config/client/wikibase/extra-install-repo.sh
While chasing down T277362 yesterday I was trying to debug this locally
and ended up with these changes that moves the interwiki link creation
from the extra-install scripts to the actual test in the hopes to
understand why things were failing. It didn't but i think this change is
preferable than having things hidden in extra-install.
> Move interwiki link creation to test

- .github/workflows/built_and_test.yml
Due to us hitting the abuse limit when many workflow runs are uploading
in a short time frame.
> Turn off uploading of every build.

- Docker/build/WDQS/README.md
This needs to get merged and publish before this would make any sense. https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Wikibase/+/681655
> Update the link to point to new dumpRdf.php documentation

- Docker/build/WikibaseBundle/LocalSettings.d/Elasticsearch.php
- Docker/test/selenium/specs/repo/search.js
- example/README.md
- example/docker-compose.yml
- test/docker-compose.yml
When running bundle without MW_ELASTIC_HOST we should still be able to search
> T280932 fix broken search

- Docker/build/QuickStatements/config.json
This URL is used for both internal fetches by the QuickStatements backend and for AJAX-fetches in the frontend.
Also properly set "server" (`WB_PUBLIC_HOST_AND_PORT` is not defined anywhere).
> QuickStatements: Use public API url

- .github/workflows/built_and_test.yml
Rather than using the "version number" e.g. wmde1 if we tag with the run
number that generated the image it will
a) be easier to see what is deployed on the test system and
b) be easier to workout which artefacts should be used if we want to publish
an image
> Tag GHCR images with run number

- .github/workflows/built_and_test.yml
Will have to be merged to main to start cronning.
- Would currently not build master since the pipeline is set to build the upcoming release.
> add cron for every six hours for .env

- .github/workflows/lint.yml
- .hadolint.yml
- Docker/build/Mediawiki/Dockerfile
- Docker/build/QuickStatements/Dockerfile
- Docker/build/WDQS/Dockerfile
- Docker/build/Wikibase/Dockerfile
- Docker/build/WikibaseBundle/Dockerfile
- Docker/publish/download_artifacts/Dockerfile
- Docker/test/selenium/Dockerfile
- Dockerfile
This PR adds dockerfile linting to CI and updates some Dockerfiles to optimize their resulting image size.
In order to enable recursive - multi file linting, some changes were required in the official hadolint github action, which was forked and upstreamed to hadolint/hadolint-action/pull/34. If and when this PR is merged, the GitHub action for linting dockerfiles must be updated.
Bug: T283240 ([link](https://phabricator.wikimedia.org/T283240))
> Optimize image size

- .github/workflows/built_and_test.yml
Cron job is currently just eating cpu and not adding any value.
Same thing with the check for last stable version, we aren't bound to
these and don't intend to release 1.36.
> Remove some useless cron job + check for last stable

- example/template.env
In some environments it appears evaluation of the `.env` can lead to errors, and the comments being included in the env vars.
https://phabricator.wikimedia.org/T286334
> example .env: move comments to own lines

- Docker/test/selenium/json-reporter.js
- test/reporter/report.js
If tests are skipped they are currently not shown in the report, which
makes it trickier to determine what actually happened.
This adds skips tests and shows them at the end.
> Update reporter to show skipped tests

- Makefile
- docs/topics/publishing.md
This adds a phony download make target which makes it easiser to
download built artifacts. Now sourcing of .env variables are guaranteed
to happen in the right order and it's only one command.
> Add download make target

- Docker/build/WDQS-frontend/Dockerfile
These started failing yesterday, lets stop installing node/npm ourselves and use a prepared image as the TODO says.
```
https://github.com/wmde/wikibase-release-pipeline/runs/4229621592?check_suite_focus=true
ERROR: unable to select packages:
git-2.32.0-r0:
breaks: build-dependencies-20211116.193615[git~2.30]
npm-7.17.0-r0:
breaks: build-dependencies-20211116.193615[npm~14]
g++-10.3.1_git20210424-r2:
breaks: build-dependencies-20211116.193615[g++~10.2]
```
> Use node image to build wdqs-frontend

- .github/actions/scan-image/action.yml
- .github/workflows/built_and_test.yml
One way of trying this out with the full UI integration could be to:
1. Fork my fork https://github.com/toban/wikibase-release-pipeline/tree/add-scan
2. Enable github actions on your fork
3. Merge add-scan to main of your fork or run the main workflow on add-scan
> Add scanning of each docker image

- Docker/test/selenium/specs/elasticsearch/elasticsearch.js
- test/suite-config/elasticsearch/docker-compose.override.yml
- test/suite-config/elasticsearch/wikibase/extra-install.sh
the reinstates the old way of initializing elasticsearch by doing it in the tests rather than relying on extra-install.
> [T296066.2] Fix elasticsearch tests getting stuck

- Docker/build/Elasticsearch/Dockerfile
- Docker/build/Mediawiki/Dockerfile
- Docker/build/QuickStatements/Dockerfile
- Docker/build/WDQS-frontend/Dockerfile
- Docker/build/WDQS-proxy/Dockerfile
- Docker/build/WDQS/Dockerfile
- Docker/build/Wikibase/Dockerfile
- Docker/build/WikibaseBundle/Dockerfile
This adds org.opencontainers.image.source in an attempt to fix missing repo link on dockerhub
> Add source to all images

- Docker/build/WikibaseBundle/Dockerfile
- build/build_wikibase_bundle_docker.sh
This method of finding out what extensions were installed was deprecated
in https://github.com/wmde/wikibase-release-pipeline/pull/259 and we can
now stop writing this in the wikibase bundle docker images.
> Stop writing INSTALLED_EXTENSIONS to wikibase bundle images

- .github/workflows/built_and_test.yml
- versions/wmde4.env
- changes to build wmde.4
- bumps the MW base image to 1.36.3
> Switch back to upcoming REL1_36 release

- .github/workflows/built_and_test.yml
- Docker/test/selenium/specs/elasticsearch/elasticsearch.js
- Set a timeout for test-upgrade base + bundle
- Lower timeout of normal tests to 15 minutes, it should never take 30 minutes. 
- Increase timeouts of elasticsearch.js tests as they seem a bit flaky now.
> Tweak some timeouts for the pipeline

- example/template.env
MW_ELASTIC_HOST gets checked at runtime if it's set in order to switch between Elasticsearch / Wikibase Search. Add a comment in the template to make this more clear.
> Add comment on MW_ELASTIC_HOST

- publish/dockerhub.sh
- publish/download.sh
- publish/git_tag.sh
- publish/tar.sh
Without this if I run the dockerhub publish step
(or any other publish step) ~42GB of my disk space
gets used due to the dind conteext being a docker
volume that will never be auto cleaned.
> docker run --rm for publish steps

- .github/workflows/built_and_test.yml
- Makefile
- docs/topics/testing.md
- test/test_upgrade.sh
The env vars from the image being tested was not properly set when
testing leading to the wrong templates being used.
> Fix upgrade

- .github/workflows/lint.yml
https://github.com/hadolint/hadolint-action/pull/34
was merged and released, so we can make use of this
rather than the custom version.
> Use hadolint/hadolint-action@v1.6.0 (recursive)

- docs/topics/publishing.md
I ran into this issue when doing the wmde.5 release, where
I followed the docs, tagged the image, and then when trying
to update links to the example I realized that I could not
link to the tag (what was done previously).
Looking at the git history this is also not the first time
this has happened, and folks have deleted tags on the repo
so they could re tag after then updating the example.
So document this step in the order of releasing.
> docs: publishing: Update example images before tagging

- Docker/publish/download_artifacts/download_artifacts.py
I was running this, and clearly had something setup wrong
but the failure message was not helpful.
Now we get the error from github if returned that should
help users determine what is going on.
> Error when download_artifacts.py gets non 200 responses

- docs/topics/publishing.md
- publish/tar-nodocker.sh
When initially running through a publish I had to get some
outside help (tobias and tom).
I managed to get through the second run by following the
docs that are in this commit.
Some things were in the wrong order before, for example you must
set your github api token before being able to download artifacts,
but this env var wasn't detailed until half way down the file.
Also seemingly some developers would not be able to run the tar
publishing setup using the documented methods, for example if not
having their ssh keys on disk, or using a yubi key.
Thus I publish an alternative path for this step in the commit.
> Docs: Rewrite publishing.md as run through again

- Docker/build/QuickStatements/entrypoint.sh
bash -v takes env var name
https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html#:~:text=Set%20Builtin).-,%2Dv,-varname
> fix quickstatements oauth env var test

- docs/topics/publishing.md
Wrong order of source commands might generated not wanted package names that get published
> publishing.md docs, load variables.env before release env

- .github/workflows/built_and_test.yml
This was added to resolve some caching issues while updating a
github action, but should not be needed any more.
Cleanup to avoid confusing people as to why this is in the key.
> This -temp-bump is not longer needed

- .github/workflows/built_and_test.yml
This step often causes the workflow to timeout at
20 mins.
It happens due to something getting stuck in this step.
This step generally takes 5 mins or less to complete.
Force it to timeout earlier so we can retry CI sooner
> Set 10min timeout for the make test-upgrade steps

- .github/workflows/built_and_test.yml
- test/docker_logs.sh
This would help debug issues such as
https://github.com/wmde/wikibase-release-pipeline/pull/364
> Always output docker logs in CI

- docs/topics/test-system.md
By recommending to use a bash script instead of manually typing 50+ lines of shell commands
> Simplify test system set up docs

- README.md
- build/build_elasticsearch_docker.sh
- build/build_quickstatements.sh
- build/build_quickstatements_docker.sh
- build/build_wdqs_docker.sh
- build/build_wdqs_frontend.sh
- build/build_wdqs_proxy_docker.sh
- build/build_wikibase.sh
- build/build_wikibase_bundle_docker.sh
- build/build_wikibase_docker.sh
The release pipeline has a setting called GZIP_COMPRESSION_RATE that can be set in local.env. Using this setting gzip invocations are configured. The user can choose the compression rate/speed tradeoff. 1 being fast and weak compression, 9 being slow and strong compression. This change extends the usage of this configuration value to the remaining gzip invocations as well as fixes the handing over of the actual value to gzip by removing the extra 'f' (not required or supported according to man gzip(1)).
> T341222: extend gzip compression rate usage

- .dockerignore
- .gitignore
It should not be commited nor put into image builds.
> T341654: git/docker ignore mwlog folder

- CHANGES.md
- versions/wmde12.env
Changing env variables and release docs to accommodate to mw1.38.7
> T334778: wmde12 security release for mw 1.38.7

- Makefile
- lint.sh
https://phabricator.wikimedia.org/T343802
- Makes project-wide linking available in local dev for using `make lint`, which does lints what our current Github lint action does, i.e.:
-  JavaScript in `Docker/test/selenium` and `diagrams` with ESLint
- `Dockerfile`s everywhere with hadolint
- `*.sh` with Spellchecker
- Runs linting before each test run (except when ran within a `GITHUB_ACTION`)
- DOES NOT add linting as a Github pre-commit hook, this is an area for possible follow-up another time
- DOES NOT re-use this shell script as the Github Action linting, and this too should be considered at some point to keep our CI more like our local dev environment
> T343802 - Add local linting script and run before each test run

- Docker/build/WikibaseBundle/LocalSettings.d.template/CirrusSearch.php
- Docker/build/WikibaseBundle/LocalSettings.d.template/Elastica.php
- Docker/build/WikibaseBundle/LocalSettings.d.template/WikibaseCirrusSearch.php
https://phabricator.wikimedia.org/T344551
> T344551: Don't load Elasticsearch extensions when Elasticsearch isn't present

- .github/workflows/build_and_test.yml
Issue found in QA of: https://github.com/wmde/wikibase-release-pipeline/pull/449. This resolves it.
Current output `TestArtifacts.zip` output of `main` from `_build_and_test` run in Github Actions:
Expected output which this change generates:
> T343348 Fix: Results overwrite each other in TestArtifacts.zip from build_and_test Github Action output

- Docker/publish/download_artifacts/download_artifacts.py
Increases the verbosity of our download github artifacts utility script on order to ease debugging.
> warn about missing github token

- .github/workflows/build_and_test.yml
This PR fixes the broken GHCR upload on main.
- load docker images from artifacts before pushing
- fix auth variables
- run on `main` and `mw-` branches
**⚠️⚠️⚠️ needs a backport to all `mw-` branches**
> fix(github-actions): GHCR upload

- .github/workflows/build_and_test.yml
- test/suites/upgrade/old-versions/wmde.13-bundle.env
- test/suites/upgrade/old-versions/wmde.13.env
Now, as wmde.13 is released, we should test updates on main from there.
> fix: change upgrade test 1.39 base version to latest

- .github/workflows/build_and_test.yml
Finally really fixing the GHCR upload for all branches that want to merge into `mw-` branches.
https://phabricator.wikimedia.org/T351290
❗ **needs BACKPORT to `mw-1.39` and `mw-1.40`** ❗
> fix(github-actions-workflow): ghcr upload base_ref check

- Docker/publish/upload_tar/publish.sh
- docs/topics/publishing.md
- docs/topics/test-system.md
- publish/docker-compose.yml
- publish/tar-nodocker.sh
With the merge of https://github.com/wmde/wikibase-release-pipeline/commit/7686b1a33dc0ca6eed02d813dc098fa7f6c68d51 built artifact names changed. This PR fixes some docs and scripts that still used to old names.
❗ **should probably be backported to `mw-1.39` and `mw-1.40`**
> fix: gh built artifact names

- variables.env
As `wmde.14` branched of, we should change the version in main. Actually, I think we should have done this right after branching off `wmde.14`.
> chore: bump version for next release

- test/specs/quickstatements/quickstatements.ts
Covers the Quickstatements part of the acceptance tests:
* `Should be able to load the start page` matches line 2
* `Should be able to change label` matches line 7
* `Should be able to add a statement to an item` matches line 8
* `Should be able to create item with label` matches line 9
> T350879 extend Quickstatements test suite

- example/docker-compose.extra.yml
- test/suites/docker-compose.yml
After an update to NixOS 23.11 which ships Docker 24.0.5 at the moment, running WDQS in the test setup broke. This PR fixes it by setting the `ulimit` for file descriptors explicitly.
> T353625 fix: wdqs out of memory / out of fds

- build/WDQS/README.md
- test/cli.ts
- test/helpers/json-reporter.ts
- test/helpers/pages/entity/property.page.ts
- test/setup/TestEnv.ts
- test/specs/repo/property.ts
- test/specs/repo/special-property.ts
- test/types/test-results.ts
Uses Mocha "retries" for Property test, and WDIO `browser.waitUntil()` for Special:Property. 
This fixes flakiness by expecting things to be a little latent and continuing to try until expected results appear. I think this the simplest and most clear solution of the options evaluated, as well as has proved to be the most reliable in my testing.  I don't think we'll continue to see failures in this setup. Slightly better than a long `browser.pause()`, which could achieve the same thing for Special:Property, but this way is more descriptive and doesn't always add the full base "pause" time to the tests. In the case of Property we need to make sure the page gets reload to check for the values each time, so `this.retries( 4 )` on the related tests also will reload the page up to 4 times …
> T353520: Property and Special:Property no longer flakey

- test/setup/wdio.conf.ts
- test/specs/repo/property.ts
- test/specs/repo/special-property.ts
Property test still flakey in CI sometimes, but failing new in new places. Updated the selectors and "expects" to what WDIO recommends and this seems to resolve the new issue. Also changed format for WDIO logging for current Suite/Spec to make it standout a bit more in the logs as well as to not be uppercased so easy to search. Helpful when debugging this. Won't be surprised if there is still something flakey here, but also it's likely this is the end of the troubles with Property 🤞🏼
> T353520: Still some flakey. Fixes more 🤤

- .github/workflows/build_and_test.yml
This PR is part of https://phabricator.wikimedia.org/T351720
This is just a small step in order to close the ticket.
Currently we only tag our containers on GHCR with CI job run id.
This run number is not intuitive, a version string should be easier to handle, especially during testing of prerelease builds (the main role of GHCR for us at the moment).
With this PR, container tags on GHCR will look like this:
> T351720 tag GHCR containers with version too

- test/specs/repo/property.ts
Using an arrow function makes `this.retries` non-functional; this just corrects that error.
> Property Test Retry Fix

- example/template.env
- variables.env
Will fail until #624 is merged and images for WMDE.17 are released on dockerhub. Merge after that.
Delete the wmde.17 tag before merging this, this will be a re-release. Fix for that pending.
> Release WMDE.17 Example Update

- .github/workflows/build_test_publish_release.yml
- build.sh
- test/Dockerfile
- test/specs/repo/special-property.ts
- update_commits.py
- variables.env
Commits from main include:
- Minor updates to `build_test_publish_release.yml`
- Organization and commenting of `variables.env`
- The `update_commits.py` script, and the updates to `build.sh` to use it, to make updating `variables.env` easier
Omitted:
- Linting and formatting changes
- Removal of docs/diagrams
- Updates to build Dockerfiles
- Updates to tests:
- Moving from `assert` to `expect`
- Universal kebab-case
- Return types
- `function () {}` notation instead of `() => {}`
- npm package updates
- use of `page.open()`
-
> Pull Current Release Tooling into MW-1.40 Prep

- .github/workflows/build_test_publish_release.yml
Currently we are publishing our images to dockerhub using a personal account. We are changing the credentials for that personal account into a generic one.
> T358475 replace personal dockerhub account with generic one

- test/specs/confirm_edit/confirm-edit.ts
- test/specs/elasticsearch/elasticsearch.ts
- test/specs/fedprops/item.ts
- test/specs/fedprops/prefetching.ts
- test/specs/pingback/pingback.ts
- test/specs/quickstatements/quickstatements.ts
- test/specs/repo/api.ts
- test/specs/repo/extensions/babel.ts
- test/specs/repo/extensions/entityschema.ts
- test/specs/repo/extensions/scribunto.ts
- test/specs/repo/extensions/syntax-highlight.ts
- test/specs/repo/extensions/universal-language-selector.ts
- test/specs/repo/extensions/visual-editor.ts
- test/specs/repo/extensions/wikibase-edtf.ts
- test/specs/repo/extensions/wikibase-local-media.ts
- test/specs/repo/extensions/wikibase-manifest.ts
- test/specs/repo/property.ts
- test/specs/repo/queryservice.ts
- test/specs/repo/recent-changes.ts
- test/specs/repo/search.ts
- test/specs/repo/special-item.ts
- test/specs/repo/special-property.ts
- test/specs/repo_client/extensions/scribunto-item.ts
- test/specs/repo_client/interwiki-links.ts
- test/specs/repo_client/item.ts
- test/specs/upgrade/pre-upgrade.ts
- test/specs/upgrade/queryservice-post-upgrade.ts
- test/specs/upgrade/queryservice-pre-and-post-upgrade.ts
- test/specs/upgrade/upgrade.ts
Using `() => {}` instead of `function () {}` for tests means the context is incorrect, so things like `this.retries()` don't work.
We made this change to `main` a while ago - it never got down to mw-1.40
> Cleanup 1.40 test fragility

- CHANGES.md
- build.sh
https://phabricator.wikimedia.org/T365569
| Image               | WBS Version | Upstream Version     | Base Image                    | Distribution    |
| ------------------- | ----------- | -------------------- | ----------------------------- | --------------- |
| WBS Wikibase        | 3.0.0       | MediaWiki 1.42.1     | PHP 8.3.8 apache              | Debian Bookworm |
| WBS WDQS            | 1.0.0       | WDQS 0.3.142         | JRE Eclipse Temurin 8u412-b08 | Debian Bookworm |
| WBS WDQS Frontend   | 1.0.0       | N/A                  | Nginx 1.27.0                  | Debian Bookworm |
| WBS WDQS Proxy      | 1.0.0       | N/A                  | Nginx 1.27.0                  | Debian Bookworm |
| WBS QuickStatements | 1.0.0       | N/A                  | PHP 8.3.8 Apache …
> TEST: Release WBS Deploy 3.0.0

- deploy/docker-compose.yml
This is simply a reduction of noise in Deploy's Docker Compose file, but also intended as a small step towards isolating our Traefik configuration such that a user could turn it off or switch it out for their own Reverse Proxy service or custom Traefik configuration. 
I think this is better, with the only question of whether it goes out with the v1/2/3 releases.  
_If you have an opinion as to whether this should be moved into the release, please note that and why/why not in your review. Either way this will not be merged until there is a clear decision across the team._
> Reduces repeated Traefik tags in Deploy docker-compose.yml

- deploy/docker-compose.yml
On first lauch, wikibase needs to create indices in elasticsearch.
This patch models this dependency explicitly in order to prevent a race condition that lead to failures on Ubuntu 22.04 with docker-ce.
https://phabricator.wikimedia.org/T371162
> fix(deploy): wikibase waits for elasticserch

- build/WDQS/README.md
- deploy/README.md
This adds some documentations about the issue where WDQS crashes when restarted with an empty database that never synced entities from MediaWiki.
https://phabricator.wikimedia.org/T354266
> docs(wdqs): details about the empty sync issue

- deploy/template.env
Clearly state that the domain names need to be distinct. Otherwise traefik reverse proxy will run into routing issues.
> docs(deploy): clarify domain names

- deploy/README.md
This removes the suggestion to use --wait with docker compose up. While this could be convenient, it hides the logs from the users. As a result, users tend to not post the relevant logs in tickets they create.
> docs(deploy): do not use --wait with up

- build/wdqs-frontend/custom-config.json
Low hanging fruit workaround for #664
> fix(wdqs-frontend): do not link to wikidata querybuilder

- .github/workflows/create_release.yml
A small thing. I had the DockerHub auth step in the Make Release workflow and it is now longer necessary. This removes it.
> chore(pipeline): Remove extraneous DockerHub auth in Release workflow

- build/wdqs/Dockerfile
- build/wdqs/README.md
- build/wdqs/entrypoint.sh
Until now, the WDQS image started as root. In the entrypoint priveleges were dropped and we switched to the "blazegraph" user. With this patch, we switch to the "blazegraph" user already during build. So the container always uses this user and does not start as root anymore.
This fixes some issues when running an interactive bash inside the container and simplifies the updater reset workaround.
https://phabricator.wikimedia.org/T362963
> fix: drop privileges during docker build

- build/wdqs/README.md
- build/wdqs/runUpdate.sh
- deploy/docker-compose.yml
- test/specs/repo/queryservice.ts
- test/specs/repo/special-new-property.ts
- test/suites/docker-compose.override.yml
- test/test-services.env
Allow setting the concept URI of entities in WDQS explicitly and distinct from the hostname used to contact wikibase.
This also fixes the problem WDQS not accepting entities when the wikibase host had a DNS name different from `wikibase` (which should be always the case, because `wikibase` is not a FQDN).
**Note: In deploy, items and properties in WDQS will now have the public wikibase hostname with https protocol as prefix. E.g. https://wikibase.example/**
Related:
- https://phabricator.wikimedia.org/T376016
- https://github.com/wmde/wikibase-release-pipeline/issues/385
- https://phabricator.wikimedia.org/T197682
- https://phabricator.wikimedia.org/T376106
BREAKING CHANGE: env var WIKIBASE_CONCEPT_URI now mandatory to run wdqs updater
> feat!: set wdqs concept URI

- deploy/docker-compose.yml
In order to finally release the fix from #771 to deploy users.
Could this be merged with #771?
> chore: bump wdqs to version 2

- deploy/docker-compose.yml
This is a follow up to #795 and #771.
Unfortunately the original bug https://phabricator.wikimedia.org/T376016 remains until we release this one as well.
> fix: bump wdqs-updater version to 2 as well

- deploy/README.md
This ensures that docker compose always checks for new images when starting the WBS Deploy stack. Actually, we expected this behavior being present already. It is also already documented like that. That's why I consider this a fix and not a feat.
> docs: fix update instructions

- Dockerfile
On some machines, installing nx in the runner fails. Apparently, this is a known issue https://github.com/nrwl/nx/issues/27040. This PR adds the workaround mentioned.
> fix: workaround nx install error

- .github/config.yml
Adds a welcome bot to the repository which welcomes new contributors and shares links with docs, community, etc.
GitHub has an option to add GitHub Apps to repositories. 'Welcome' is a [GitHub app](https://github.com/behaviorbot/welcome?installation_id=56797506&setup_action=install) that helps us automatically reply to first time contributors of the repository. We do this by adding a config.yml file.
Ticket: https://phabricator.wikimedia.org/T379163
> feat: add welcome bot for new contributors

- build/wdqs/entrypoint.sh
- deploy/docker-compose.yml
~~As reported in #798, default prefixes injected by WDQS did not align with the `WIKIBASE_CONCEPT_URI` setting added in #771. This PR fixes it.~~
As reported in #798, the "standard prefixes" injected by WDQS do not align with the WIKIBASE_CONCEPT_URI setting introduced in #771, nor do they match the corresponding values for Wikidata. Currently, the WDQS-injected "standard prefixes" (such as `wd:`) reference `http://wikidata/`, which is the internal hostname of the wikibase/mediawiki container within the Docker network.
Particularly in the context of federation, it is essential to maintain the "standard prefixes" for referencing Wikidata [1] [2]. To accommodate the local Wikibase instance, prefixes can be set inline, as is currently done on wikibase.cloud [2]. This pull request addresses …
> fix: injected standard prefixes reference wikidata

- deploy/docker-compose.yml
As reported in https://phabricator.wikimedia.org/T382200, traefik is the only service that remains stopped after a docker daemon restart (e.g. when rebooting the host). This change fixes traefik's restart policy to match the other services so that also traefik starts up automatically.
> fix: set traefik restart policy to 'unless-stopped'

- .github/workflows/build_test_main.yml
Before actually publishing the image to dockerhub, run our usual build and integration tests. This adds a simple safety net to not publish images failing tests.
Note that this simple solution builds the images twice, once for testing (images are pushed to GHCR as usual) and another time for publishing to dockerhub. Reducing the build to only once (which would be the way cleaner solution) would require quite some refactoring in the build script and some extra thought wrt multi platform builds. 
https://phabricator.wikimedia.org/T378941
> feat(ci): always test before publish

- build/wikibase/Dockerfile
Seems to stabilize image builds. Sometimes gerrit would just drop the connection in the middle of the checkout otherwise.
> feat: depth 1 checkouts in wikibase-image build

- README.md
- build/quickstatements/build.env
- build/wdqs-frontend/build.env
- build/wikibase/build.env
To view the changes nicely rendered, [go here](https://github.com/wmde/wikibase-release-pipeline/tree/docs-howto-release?tab=readme-ov-file#-release-and-publish-process).
> docs: howto release
